languageCode = "es"
languageName = "Español"
weight = 1
title = "Luis"

[params]
  displayName = "Español"
  isoCode = "es"
  rtl = false
  dateFormat = "2 Enero 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Un tema potente y ligero para Hugo."

[author]
  name = "Luis Alberto"
  image = "img/blowfish_logo.png"
  headline = "Un tema potente y ligero para Hugo."
  bio = "A powerful, lightweight theme for Hugo."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]